Bump `poetry2nix` to the most recent version
Apparently the old `poetry2nix` is not able to handle the `zipp`
dependency of the `importlib-resources` package, which is pulled in by
the most recent version of `jsonschema` (4.2.1):

> ERROR: Could not find a version that satisfies the requirement zipp>=3.1.0; python_version < "3.10" (from importlib-resources==0.0.0) (from versions: none)
> ERROR: No matching distribution found for zipp>=3.1.0; python_version < "3.10" (from importlib-resources==0.0.0)

The updated `poetry2nix` avoids that error.